One of the design goals of Micronaut was to eliminate the artificial separation imposed by traditional frameworks between function and unit tests due to slow startup times and memory consumption.


With that in mind it is generally pretty easy to start Micronaut in a unit test and one of the goals of Micronaut was to as much as possible not require a test framework to test Micronaut. For example in http://spockframework.org[Spock] you can simply do:

[source,groovy]
----
@Shared // <1>
@AutoCleanup // <2>
EmbeddedServer embeddedServer = ApplicationContext.run(EmbeddedServer)
----

<1> The field is declared as shared so to server is started only once for all methods in the class
<2> The `@AutoCleanup` annotation ensures the server is shutdown after the test suite completes.

However, there are cases where having some additional features to test Micronaut come in handy, such as mocking bean definitions and so on.

This project includes a pretty simple set of extensions for JUnit 5, Spock and Kotest:

* Automatically start and stop the server for the scope of a test suite
* Use mocks to replace existing beans for the scope of a test suite
* Allow dependency injection into a test instance

This is achieved through a set of annotations:

* `@MicronautTest` - Can be added to any test:
** `io.micronaut.test.extensions.spock.annotation.MicronautTest` for Spock.
** `io.micronaut.test.extensions.junit5.annotation.MicronautTest` for JUnit 5.
** `io.micronaut.test.extensions.kotest.annotation.MicronautTest` for Kotest.
** `io.micronaut.test.extensions.kotest5.annotation.MicronautTest` for Kotest 5.
* `io.micronaut.test.annotation.@MockBean` - Can be added to methods or inner classes of a test class to define mock beans that replace existing beans for the scope of the test.

These annotations use internal Micronaut features and do not mock any part of Micronaut itself. When you run a test within `@MicronautTest` it is running your real application.

In some tests you may need a reference to the `ApplicationContext` and/or the `EmbeddedServer` (for example, to create an instance of an `HttpClient`). Rather than defining these as properties of the test (such as a `@Shared` property in Spock), when using `@MicronautTest` you can reference the server/context that was started up for you, and inject them directly in your test.

[source,groovy]
----
@Inject
EmbeddedServer server //refers to the server that was started up for this test suite

@Inject
ApplicationContext context //refers to the current application context within the scope of the test
----

### Eager Singleton Initialization

If you enable https://docs.micronaut.io/latest/guide/index.html#eagerInit[eager singleton initialization] in your application, the Micronaut Framework eagerly initializes all singletons at startup time. This can be useful for applications that need to perform some initialization at startup time, such as registering a bean with a third party library.

However, as tests annotated with `@MicronautTest` are implicitly in the `Singleton` scope, this can cause problems injecting some beans (for example an `HttpClient`) into your test class.

To avoid this, you can either disable eager singleton initialization for your tests, or you will need to manually get an instance of the bean you would normally inject.  As an example, to get an `HttpClient` you could do:

[source,java]
----
@Inject
EmbeddedServer server; // <1>

Supplier<HttpClient> client = SupplierUtil.memoizedNonEmpty(() ->
    server.getApplicationContext().createBean(HttpClient.class, server.getURL())); // <2>

@Test
void testEagerSingleton() {
    Assertions.assertEquals("eager", client.get().toBlocking().retrieve("/eager")); // <3>
}
----

<1> Inject the `EmbeddedServer` as normal
<2> Create a `Supplier` that will create the `HttpClient` when it is first called
<3> Use the `Supplier` to get the `HttpClient` and make the request
