One of the design goals of Micronaut was to eliminate the artificial separation imposed by traditional frameworks between function and unit tests due to slow startup times and memory consumption.


With that in mind it is generally pretty easy to start Micronaut in a unit test and one of the goals of Micronaut was to as much as possible not require a test framework to test Micronaut. For example in http://spockframework.org[Spock] you can simply do:

[source,groovy]
----
@Shared // <1>
@AutoCleanup // <2>
EmbeddedServer embeddedServer = ApplicationContext.run(EmbeddedServer)
----

<1> The field is declared as shared so to server is started only once for all methods in the class
<2> The `@AutoCleanup` annotation ensures the server is shutdown after the test suite completes.

However, there are cases where having some additional features to test Micronaut come in handy, such as mocking bean definitions and so on.

This project includes a pretty simple set of extensions for JUnit 5 and Spock:

* Automatically start and stop the server for the scope of a test suite
* Use mocks to replace existing beans for the scope of a test suite
* Allow dependency injection into a test instance

This is achieved through a set of annotations found in the `io.micronaut.test.annotation` package:

* `@MicronautTest` - Can be added to any Spock or JUnit 5 test.
* `@MockBean` - Can be added to methods or inner classes of a test class to define mock beans that replace existing beans for the scope of the test.

If you have either of the libraries for spock or JUnit 5 in your dependencies, you must include the appropriate dependency for the `@MicronautTest` annotation to work. It is not enough to have just `micronaut-test-spock` if you have JUnit 5 libraries loaded, you must also include `micronaut-test-junit5` and vice versa, or remove the references to JUnit 5 completely.

These annotations use internal Micronaut features and do not mock any part of Micronaut itself. When you run a test within `@MicronautTest` it is running your real application.

In some tests you may need a reference to the `ApplicationContext` and/or the `EmbeddedServer` (for example, to create an instance of an `HttpClient`). Rather than defining these as properties of the test (such as a `@Shared` property in Spock), when using `@MicronautTest` you can reference the server/context that was started up for you, and inject them directly in your test.  

[source,groovy]
----
@Inject 
EmbeddedServer server //refers to the server that was started up for this test suite

@Inject 
ApplicationContext context //refers to the current application context within the scope of the test
----