One of the design goals of Micronaut was to eliminate the artificial separation imposed by traditional frameworks between function and unit tests due to slow startup times and memory consumption.


With that in mind it is generally pretty easy to start Micronaut in a unit test and one of the goals of Micronaut was to as much as possible not require a test framework to test Micronaut. For example in http://spockframework.org[Spock] you can simply do:

[source,groovy]
----
@Shared // <1>
@AutoCleanup // <2>
EmbeddedServer embeddedServer = ApplicationContext.run(EmbeddedServer)
----

<1> The field is declared as shared so to server is started only once for all methods in the class
<2> The `@AutoCleanup` annotation ensures the server is shutdown after the test suite completes.

However, there are cases where having some additional features to test Micronaut come in handy, such as mocking bean definitions and so on.

This project includes a pretty simple set of extensions for JUnit 5, Spock, Kotest and KotlinTest:

* Automatically start and stop the server for the scope of a test suite
* Use mocks to replace existing beans for the scope of a test suite
* Allow dependency injection into a test instance

This is achieved through a set of annotations:

* `@MicronautTest` - Can be added to any test:
** `io.micronaut.test.extensions.junit5.annotation.MicronautTest` for JUnit 5, Kotest and Kotlintest.
** `io.micronaut.test.extensions.spock.annotation.MicronautTest` for Spock.
* `io.micronaut.test.annotation.@MockBean` - Can be added to methods or inner classes of a test class to define mock beans that replace existing beans for the scope of the test.

These annotations use internal Micronaut features and do not mock any part of Micronaut itself. When you run a test within `@MicronautTest` it is running your real application.

In some tests you may need a reference to the `ApplicationContext` and/or the `EmbeddedServer` (for example, to create an instance of an `HttpClient`). Rather than defining these as properties of the test (such as a `@Shared` property in Spock), when using `@MicronautTest` you can reference the server/context that was started up for you, and inject them directly in your test.  

[source,groovy]
----
@Inject 
EmbeddedServer server //refers to the server that was started up for this test suite

@Inject 
ApplicationContext context //refers to the current application context within the scope of the test
----

=== Release History

==== 1.3.x

* `io.micronaut.test.annotation.MicronautTest` has been deprecated. Use the test framework-specific annotation instead.

==== 1.2.x

* Micronaut 1.3.3 or above required.
* Support for Kotest
* Deprecated support for Kotlin Test

==== 1.1.x

* Micronaut 1.1.x or above required.
* Upgrade to JUnit 5.5.
* Support for Dependency Injection in Constructors and Method Parameters for JUnit 5.
* Support for Kotlin Test.

==== 1.0.x

* Initial Version with support for JUnit 5 and Spock.
