This project features utilities for helping test Micronaut applications.

It is generally pretty easy to start Micronaut in a unit test and one of the goals of Micronaut was to as much as possible not require a test framework to test Micronaut. For example in http://spockframework.org[Spock] you can simply do:

[source,groovy]
----
@Shared // <1>
@AutoCleanup // <2>
EmbeddedServer embeddedServer = ApplicationContext.run(EmbeddedServer)
----

<1> The field is declared as shared so to server is started only once for all methods in the class
<2> The `@AutoCleanup` annotation ensures the server is shutdown after the test suite completes.

However, there are cases where having some tools to test Micronaut come in handy, such as mocking bean definitions and so on.

This project includes a pretty simply set of extensions for JUnit 5, Spock and Spek (TODO), that allow you to:

* Automatically start and stop the server for the scope of a test suite
* Use mocks to replace existing beans for the scope of a test suite
* Allow dependency injection into a test instance

This is achieved through a set of annotations found in the `io.micronaut.test.annotation` package:

* `@MicronautTest` - Can be added to any Spock, JUnit 5 or Spek test to indicate the test is a Micronaut test.
* `@MockBean` - Can be added to methods or inner classes of a test class to define mock beans that replace existing beans for the scope of the test.
