=== Setting up KotlinTest

To get started using KotlinTest you need the following dependencies in your build configuration:

.build.gradle
[source,groovy,subs="attributes"]
----
dependencies {
    kaptTest "io.micronaut:micronaut-inject-java"
    testImplementation "io.micronaut.test:micronaut-test-kotlintest:{version}"
    testImplementation "io.mockk:mockk:1.9.3"
    testImplementation "io.kotlintest:kotlintest-runner-junit5:3.3.2"
}

// use JUnit 5 platform
test {
    useJUnitPlatform()
}
----

Or for Maven:

.pom.xml
[source,xml]
----
<dependency>
    <groupId>io.micronaut.test</groupId>
    <artifactId>micronaut-test-kotlintest</artifactId>
    <version>{version}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.mockk</groupId>
    <artifactId>mockk</artifactId>
    <version>1.9.3</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.kotlintest</groupId>
    <artifactId>kotlintest-runner-junit5</artifactId>
    <version>3.3.2</version>
    <scope>test</scope>
</dependency>
----

Note that for Maven you will also need to configure the Surefire plugin to use JUnit platform and configure the kotlin maven plugin:

.pom.xml
[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.22.2</version>
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.3.1</version>
        </dependency>
    </dependencies>
</plugin>
<plugin>
    <artifactId>kotlin-maven-plugin</artifactId>
    <groupId>org.jetbrains.kotlin</groupId>
    <version>1.3.20</version>
    <configuration>
        <compilerPlugins>
            <plugin>all-open</plugin>
        </compilerPlugins>
        <pluginOptions>
            <option>all-open:annotation=io.micronaut.aop.Around</option>
        </pluginOptions>
    </configuration>
    <executions>
        <execution>
            <id>kapt</id>
            <goals>
                <goal>kapt</goal>
            </goals>
            <configuration>
                <sourceDirs>
                    <sourceDir>${project.baseDir}/src/main/kotlin</sourceDir>
                </sourceDirs>
                <annotationProcessorPaths>
                    <annotationProcessorPath>
                        <groupId>io.micronaut</groupId>
                        <artifactId>micronaut-inject-java</artifactId>
                        <version>${micronaut.version}</version>
                    </annotationProcessorPath>
                    <annotationProcessorPath>
                        <groupId>io.micronaut</groupId>
                        <artifactId>micronaut-validation</artifactId>
                        <version>${micronaut.version}</version>
                    </annotationProcessorPath>
                </annotationProcessorPaths>
            </configuration>
        </execution>
        <execution>
            <id>compile</id>
            <goals>
                <goal>compile</goal>
            </goals>
            <configuration>
                <sourceDirs>
                    <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                    <sourceDir>${project.basedir}/src/main/java</sourceDir>
                </sourceDirs>
            </configuration>
        </execution>
        <execution>
            <id>test-kapt</id>
            <goals>
                <goal>test-kapt</goal>
            </goals>
            <configuration>
                <sourceDirs>
                    <sourceDir>src/test/kotlin</sourceDir>
                </sourceDirs>
                <annotationProcessorPaths>
                    <annotationProcessorPath>
                        <groupId>io.micronaut</groupId>
                        <artifactId>micronaut-inject-java</artifactId>
                        <version>${micronaut.version}</version>
                    </annotationProcessorPath>
                </annotationProcessorPaths>
            </configuration>
        </execution>
        <execution>
            <id>test-compile</id>
            <goals>
                <goal>test-compile</goal>
            </goals>
            <configuration>
                <sourceDirs>
                    <sourceDir>${project.basedir}/src/test/kotlin</sourceDir>
                    <sourceDir>${project.basedir}/target/generated-sources/kapt/test</sourceDir>
                </sourceDirs>
            </configuration>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-allopen</artifactId>
            <version>${kotlinVersion}</version>
        </dependency>
    </dependencies>
</plugin>
----

=== Before You Begin

Before you can get started writing tests with KotlinTest, it is necessary to inform KotlinTest of the Micronaut extensions. The way to do that is by providing a `ProjectConfig` object in a specific package. Here is how to do so for Micronaut Test:

[source,kotlin]
----
include::test-kotlintest/src/test/kotlin/io/kotlintest/provided/ProjectConfig.kt[]
----

=== Writing a Micronaut Test with KotlinTest

Let's take a look at an example using KotlinTest. Consider you have the following interface:

.The MathService Interface
[source,kotlin]
----
include::{kotlintesttests}/MathService.kt[]
----

And a simple implementation that computes the value times 4 and is defined as Micronaut bean:

.The MathService implementation
[source,kotlin]
----
include::{kotlintesttests}/MathServiceImpl.kt[]
----

You can define the following test to test the implementation:

.The MathService specification
[source,groovy]
----
include::{kotlintesttests}/MathServiceTest.kt[]
----

<1> The test is declared as Micronaut test with `@MicronautTest`
<2> The constructor is used to inject the bean
<3> The test itself tests the injected bean


=== Environments, Classpath Scanning etc.

The `@MicronautTest` annotation supports specifying the environment names the test should run with:

```java
@MicronautTest(environments={"foo", "bar"})
```

In addition, although Micronaut itself doesn't scan the classpath, some integrations do (such as JPA and GORM), for these cases you may wish to specify either the application class:

```java
@MicronautTest(application=Application.class)
```

Or the packages:

```java
@MicronautTest(packages="foo.bar")
```

To ensure that entities can be found during classpath scanning.

=== Using Mockk Mocks

Now let's say you want to replace the implementation with a Mockk. You can do so by defining a method that returns a mock and is annotated with `@MockBean`, for example:

.The MathService specification
[source,kotlin]
----
include::{kotlintesttests}/MathMockServiceTest.kt[]
----

<1> The `@MockBean` annotation is used to indicate the method returns a mock bean. The value to the method is the type being replaced.
<2> Mockk's `mockk(..)` method creates the actual mock
<3> The math service proxy is injected into the test
<4> The call to `getMock` is used to retrieve the underlying mock
<5> Mockk is used to verify the mock is called

Note that because the bean is a method of the test, it will be active only for the scope of the test. This approach allows you to define beans that are isolated per test class.

IMPORTANT: Because Kotlin uses constructor injection, it's not possible to automatically replace the mock proxy with the mock implementation as is done with the other test implementations. The `getMock` method was created to make retrieving the underlying mock object easier.

=== Mocking Collaborators

Note that in most cases you won't define a `@MockBean` and then inject it only to verify interaction with the Mock directly, instead the Mock will be a collaborator within your application. For example say you have a `MathController`:

.The MathController
[source,kotlin]
----
include::{kotlintesttests}/MathController.kt[]
----

The above controller uses the `MathService` to expose a `/math/compute/{number}` endpoint. See the following example for a test that tests interaction with the mock collaborator:

.Mocking Collaborators
[source,kotlin]
----
include::{kotlintesttests}/MathCollaboratorTest.kt[]
----

<1> Like the previous example a Mock is defined using `@MockBean`
<2> This time we inject an instance of `RxHttpClient` to test the controller.
<3> We invoke the controller and retrieve the result
<4> The interaction with mock collaborator is verified.

The way this works is that `@MicronautTest` will inject a proxy that points to the mock instance. For each iteration of the test the mock is refreshed (in fact it uses Micronaut's built in `RefreshScope`).

=== Using `@Requires` on Tests

Since `@MicronautTest` turns tests into beans themselves, it means you can use the `@Requires` annotation on the test to enable/disable tests. For example:

[source,kotlin]
----
@MicronautTest
@Requires(env = "my-env")
class RequiresTest {
    ...
}
----

The above test will only run if `my-env` is active (you can active it by passing the system property `micronaut.environments`).

=== Defining Additional Test Specific Properties

You can define additional test specific properties using the `@Property` annotation. The following example demonstrates usage:

.Using `@Property`
[source,kotlin]
----
include::{kotlintesttests}/PropertyValueTest.kt[]
----

Alternatively you can specify additional `propertySources` in any supported format (YAML, JSON, Java properties file etc.) using the `@MicronautTest` annotation:

.Using `propertySources` stored in files
[source,kotlin]
----
include::{kotlintesttests}/PropertySourceTest.kt[]
----

The above example expects a file located at `src/test/resources/io/micronaut/kotlintest/myprops.properties`. You can however use a prefix to indicate where the file should be searched for. The following are valid values:

* `file:myprops.properties` - A relative path to a file somewhere on the file system
* `classpath:myprops.properties` - A file relative to the root of the classpath
* `myprops.properties` - A file relative on the classpath relative to the test being run.

NOTE: Because Kotlin doesn't support multiple annotations, the `@PropertySource` annotation must be used to define multiple properties.

=== Constructor Injection Caveats

There are a couple caveats to using constructor injection to be aware of.

1. In order for `TestPropertyProvider` to work, test classes must have not have any constructor arguments. This is because the class needs constructed prior to bean creation in order to add the properties to the context. Fields and methods will still be injected.

1. `@Requires()` cannot be used with constructor injection because Kotlintest requires the instance to be created regardless if the test should be ignored or not. If the requirements disable the bean, it cannot be created from the context and thus construction responsibility will be delegated to the default behavior.

=== Refreshing injected beans based on `@Requires` upon properties changes

You can use combine the use of `@Requires` and `@Property`, so that injected beans will be refreshed if there are
configuration changes that affect their `@Requires` condition.

For that to work, the test must be annotated with `@MicronautTest(rebuildContext = true)`. In that case, if there are
changes in any property for a given test, the application context will be rebuilt so that `@Requires` conditions are
re-evaluated again.

For example:

.Combining `@Requires` and `@Property` in a `@Refreshable` test class.
[source,kotlin]
----
include::{kotlintesttests}/PropertyValueRequiresTest.kt[]
----