=== Setting up Spock

To get started using Spock you need the following dependencies in your build configuration:

.build.gradle
[subs="attributes"]
----
testCompile "io.micronaut.test:test-spock:{version}
----

NOTE: If you plan to define mock beans you will also need `inject-groovy` on your `testCompile` classpath or `inject-java` for Java or Kotlin (this should already be configured if you used `mn create-app`).

Or for Maven:

.pom.xml
[source,xml]
----
<dependency>
    <groupId>io.micronaut.test</groupId>
    <artifactId>test-spock</artifactId>
    <version>{version}</version>
    <scope>test</scope>
</dependency>
----

=== Writing a Micronaut Test with Spock

Let's take a look at an example using Spock. Consider you have the following interface:

.The MathService Interface
[source,groovy]
----
include::{spocktests}/MathService.java[]
----

And a simple implementation that computes the value times 4 and is defined as Micronaut bean:

.The MathService implementation
[source,groovy]
----
include::{spocktests}/MathServiceImpl.groovy[]
----

You can define the following test to test it:

.The MathService specification
[source,groovy]
----
include::{spocktests}/MathServiceSpec.groovy[]
----

<1> The test is declared as Micronaut test with `@MicronautTest`
<2> The `@Inject` annotation is used to inject the bean
<3> The test itself tests the injected bean

=== Using Spock Mocks

Now let's say you want to replace the implementation with a Spock Mock. You can do so by defining a method that returns a Spock mock and is annotated with `@MockBean`, for example:

.The MathService specification
[source,groovy]
----
include::{spocktests}/MathMockServiceSpec.groovy[]
----

<1> The `@MockBean` annotation is used to indicate the method returns a mock bean. The value to the method is the type being replaced.
<2> Spock's `Mock(..)` method creates the actual mock
<3> The Mock is injected into the test
<4> Spock is used to verify the mock is called

=== Mocking Collaborators

Note that in most cases you won't define a `@MockBean` and then inject it only to verify interaction with the Mock directly, instead the Mock will be a collaborator within your application. For example say you have a `MathController`:

.The MathController
[source,groovy]
----
include::{spocktests}/MathController.groovy[]
----

The above controller uses the `MathService` to expose a `/math/compute/{number]` endpoint. See the following example for a test that tests interaction with the mock collaborator:

.Mocking Collaborators
[source,groovy]
----
include::{spocktests}/MathCollaboratorSpec.groovy[]
----

<1> Like the previous example a Mock is defined using `@MockBean`
<2> This time we inject an instance of `RxHttpClient` to test the controller.
<3> We invoke the controller and retrieve the result
<4> The interaction with mock collaborator is verified.

The way this works is that `@MicronautTest` will inject the `Mock(..)` instance into the test, but the controller will have a proxy that points to the `Mock(..)` instance injected. For each iteration of the test the mock is refreshed (in fact it uses Micronaut's built in `RefreshScope`).