=== Setting up Spock

To get started using Spock you need the following dependencies in your build configuration:

.build.gradle
[source,groovy,subs="attributes"]
----
testImplementation "io.micronaut.test:micronaut-test-spock"
testImplementation("org.spockframework:spock-core") {
    exclude group: "org.codehaus.groovy", module: "groovy-all"
}
----

NOTE: If you plan to define mock beans you will also need `micronaut-inject-groovy` on your `testImplementation` classpath or `micronaut-inject-java` for Java or Kotlin (this should already be configured if you used `mn create-app`).

Or for Maven:

.pom.xml
[source,xml]
----
<dependency>
    <groupId>io.micronaut.test</groupId>
    <artifactId>micronaut-test-spock</artifactId>
    <scope>test</scope>
</dependency>
----

=== Writing a Micronaut Test with Spock

Let's take a look at an example using Spock. Consider you have the following interface:

.The MathService Interface
[source,groovy]
----
include::{spocktests}/MathService.java[]
----

And a simple implementation that computes the value times 4 and is defined as Micronaut bean:

.The MathService implementation
[source,groovy]
----
include::{spocktests}/MathServiceImpl.groovy[]
----

You can define the following test to test it:

.The MathService specification
[source,groovy]
----
include::{spocktests}/MathServiceSpec.groovy[]
----

<1> The test is declared as Micronaut test with `@MicronautTest`
<2> The `@Inject` annotation is used to inject the bean
<3> The test itself tests the injected bean

=== Environments, Classpath Scanning etc.

The `@MicronautTest` annotation supports specifying the environment names the test should run with:

```java
@MicronautTest(environments=["foo", "bar"])
```

In addition, although Micronaut itself doesn't scan the classpath, some integrations do (such as JPA and GORM), for these cases you may wish to specify either the application class:

```java
@MicronautTest(application=Application.class)
```

Or the packages:

```java
@MicronautTest(packages="foo.bar")
```

To ensure that entities can be found during classpath scanning.

=== Using Spock Mocks

Now let's say you want to replace the implementation with a Spock Mock. You can do so by defining a method that returns a Spock mock and is annotated with `@MockBean`, for example:

.The MathService specification
[source,groovy]
----
include::{spocktests}/MathMockServiceSpec.groovy[]
----

<1> The `@MockBean` annotation is used to indicate the method returns a mock bean. The value to the method is the type being replaced.
<2> Spock's `Mock(..)` method creates the actual mock
<3> The Mock is injected into the test
<4> Spock is used to verify the mock is called

=== Mocking Collaborators

Note that in most cases you won't define a `@MockBean` and then inject it only to verify interaction with the Mock directly, instead the Mock will be a collaborator within your application. For example say you have a `MathController`:

.The MathController
[source,groovy]
----
include::{spocktests}/MathController.groovy[]
----

The above controller uses the `MathService` to expose a `/math/compute/{number]` endpoint. See the following example for a test that tests interaction with the mock collaborator:

.Mocking Collaborators
[source,groovy]
----
include::{spocktests}/MathCollaboratorSpec.groovy[]
----

<1> Like the previous example a Mock is defined using `@MockBean`
<2> This time we inject an instance of `RxHttpClient` to test the controller.
<3> We invoke the controller and retrieve the result
<4> The interaction with mock collaborator is verified.

The way this works is that `@MicronautTest` will inject the `Mock(..)` instance into the test, but the controller will have a proxy that points to the `Mock(..)` instance injected. For each iteration of the test the mock is refreshed (in fact it uses Micronaut's built in `RefreshScope`).


=== Using `@Requires` on Tests

Since `@MicronautTest` turns tests into beans themselves, it means you can use the `@Requires` annotation on the test to enable/disable tests. For example:

[source,java]
----
@MicronautTest
@Requires(env = "my-env")
class RequiresSpec extends Specification {
    ...
}
----

The above test will only run if `my-env` is active (you can active it by passing the system property `micronaut.environments`).

=== Defining Additional Test Specific Properties

You can define additional test specific properties using the `@Property` annotation. The following example demonstrates usage:

.Using `@Property`
[source,java]
----
include::{spocktests}/PropertySpec.groovy[]
----

Note that when a `@Property` is defined at the test method level, it causes a `RefreshEvent` to be triggered which will update any `@ConfigurationProperties` related  to the property.


Alternatively you can specify additional `propertySources` in any supported format (YAML, JSON, Java properties file etc.) using the `@MicronautTest` annotation:

.Using `propertySources` stored in files
[source,java]
----
include::{spocktests}/PropertySourceSpec.groovy[]
----

The above example expects a file located at `src/test/resources/io/micronaut/spock/myprops.properties`. You can however use a prefix to indicate where the file should be searched for. The following are valid values:

* `file:myprops.properties` - A relative path to a file somewhere on the file system
* `classpath:myprops.properties` - A file relative to the root of the classpath
* `myprops.properties` - A file relative on the classpath relative to the test being run.

=== Refreshing injected beans based on `@Requires` upon properties changes

You can use combine the use of `@Requires` and `@Property`, so that injected beans will be refreshed if there are
configuration changes that affect their `@Requires` condition.

For that to work, the test must be annotated with `@MicronautTest(rebuildContext = true)`. In that case, if there are
changes in any property for a given test, the application context will be rebuilt so that `@Requires` conditions are
re-evaluated again.

For example:

.Combining `@Requires` and `@Property` in a `@Refreshable` test class.
[source,java]
----
include::{spocktests}/PropertyValueRequiresSpec.groovy[]
----