plugins {
    id "io.micronaut.build.internal.module"
    id("org.sonatype.gradle.plugins.scan")
}
String ossIndexUsername = System.getenv("OSS_INDEX_USERNAME") ?: project.properties["ossIndexUsername"]
String ossIndexPassword = System.getenv("OSS_INDEX_PASSWORD") ?: project.properties["ossIndexPassword"]
boolean sonatypePluginConfigured = ossIndexUsername != null && ossIndexPassword != null
if (sonatypePluginConfigured) {
    ossIndexAudit {
        username = ossIndexUsername
        password = ossIndexPassword
        excludeCompileOnly = true
    }
}


repositories {
    mavenCentral()
}

configurations.all {
    resolutionStrategy {
        dependencySubstitution {
            // The internal Micronaut module plugin automatically adds a dependency on
            // Micronaut test, which causes conflicts in this project, since we _are_ Micronaut test.
            rootProject.subprojects.name.each {
                if (it.contains('-bom')) {
                    substitute(platform(module("io.micronaut.test:$it"))).using(platform(project(":$it")))
                } else {
                    substitute(module("io.micronaut.test:$it")).using(project(":$it"))
                }
            }
        }
    }
}
