Now let's say you want to replace the implementation with a Mockk. You can do so by defining a method that returns a mock and is annotated with `@MockBean`, for example:

.The MathService specification
[source,kotlin]
----
include::{kotest5tests}/MathMockServiceTest.kt[]
----

<1> The `@MockBean` annotation is used to indicate the method returns a mock bean. The value to the method is the type being replaced.
<2> Mockk's `mockk(..)` method creates the actual mock
<3> The math service proxy is injected into the test
<4> The call to `getMock` is used to retrieve the underlying mock
<5> Mockk is used to verify the mock is called

Note that because the bean is a method of the test, it will be active only for the scope of the test. This approach allows you to define beans that are isolated per test class.

IMPORTANT: Because Kotlin uses constructor injection, it's not possible to automatically replace the mock proxy with the mock implementation as is done with the other test implementations. The `getMock` method was created to make retrieving the underlying mock object easier.
