You can define additional test specific properties using the `@Property` annotation. The following example demonstrates usage:

.Using `@Property`
[source,java]
----
include::{spocktests}/PropertySpec.groovy[]
----

Note that when a `@Property` is defined at the test method level, it causes a `RefreshEvent` to be triggered which will update any `@ConfigurationProperties` related  to the property.


Alternatively you can specify additional `propertySources` in any supported format (YAML, JSON, Java properties file etc.) using the `@MicronautTest` annotation:

.Using `propertySources` stored in files
[source,java]
----
include::{spocktests}/PropertySourceSpec.groovy[]
----

The above example expects a file located at `src/test/resources/io/micronaut/spock/myprops.properties`. You can however use a prefix to indicate where the file should be searched for. The following are valid values:

* `file:myprops.properties` - A relative path to a file somewhere on the file system.
* `classpath:myprops.properties` - A file relative to the root of the classpath.
* `myprops.properties` - A file relative on the classpath relative to the test being run.
