plugins {
    id "io.micronaut.build.internal.bom"
}

repositories {
    gradlePluginPortal() // needed for checkBom task to resolve plugin dependencies defined in kotest-pom
}

micronautBom {
    suppressions {
        acceptedLibraryRegressions.add("micronaut-test-junit5") // has been renamed to micronaut-test-junit
        acceptedLibraryRegressions.add("micronaut-test-rest-assured")
        acceptedLibraryRegressions.add("micronaut-test-kotest")
        acceptedLibraryRegressions.add("junit-platform-runner")
        acceptedLibraryRegressions.add("junit-platform-jfr")
        acceptedVersionRegressions.add("junit-platform")
    }
}
