plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation(libs.micronaut.library.plugin)
    // Ensure Kotlin Gradle plugin is on buildSrc classpath so convention plugins can apply it without versions
    implementation(libs.kotlin.gradle.plugin)
}
